from __future__ import annotations

import argparse
import json
import re
import struct
import shutil
from pathlib import Path
from typing import Any, Optional

import numpy as np


INIT_EXPORTS = {
    "TRANX": ["TRANX", "TRANSMISSIBILITY_I"],
    "TRANY": ["TRANY", "TRANSMISSIBILITY_J"],
    "TRANZ": ["TRANZ", "TRANSMISSIBILITY_K"],

    "MULTX": ["MULTX", "TRANSMISSIBILITY_MULTIPLIER_I"],
    "MULTY": ["MULTY", "TRANSMISSIBILITY_MULTIPLIER_J"],
    "MULTZ": ["MULTZ", "TRANSMISSIBILITY_MULTIPLIER_K"],

    "PORO": ["PORO", "POROSITY"],
    "PORO_MULT": ["PORO_MULT", "POROSITY_MULTIPLIER"],

    "PERM_X": ["PERMX", "PERM_X", "PERM_I"],
    "PERM_Y": ["PERMY", "PERM_Y", "PERM_J"],
    "PERM_Z": ["PERMZ", "PERM_Z", "PERM_K"],

    "FIPNUM": ["FIPNUM", "FLUID_IN_PLACE_REGION"],
    "SATNUM": ["SATNUM", "SATURATION_FUNCTION_DRAINAGE_TABLE_NO"],
    "IMBNUM": ["IMBNUM", "SATURATION_FUNCTION_IMBIBITION_TABLE_NO"],
}

DYNAMIC_EXPORTS = {
    "PRESSURE": ["PRESSURE"],
    "SWAT": ["SWAT", "WATER_SATURATION"],
    "SOIL": ["SOIL", "OIL_SATURATION"],
    "SGAS": ["SGAS", "GAS_SATURATION"],
}


def norm_name(name: str) -> str:
    return re.sub(r"[^A-Z0-9_]", "_", str(name).upper())


def safe_float_array(values: Any) -> np.ndarray:
    arr = np.asarray(values, dtype=float).reshape(-1)
    arr[~np.isfinite(arr)] = 0.0
    return arr


def format_grdecl_value(v: float) -> str:
    v = float(v)

    if abs(v) < 1e-14:
        return "0"

    if abs(v - round(v)) < 1e-12:
        return str(int(round(v)))

    return f"{v:.10g}"


def compress_grdecl_values(values: np.ndarray, tolerance: float = 1e-12) -> list[str]:
    values = safe_float_array(values)

    if len(values) == 0:
        return []

    tokens = []
    current = float(values[0])
    count = 1

    for raw in values[1:]:
        v = float(raw)

        if abs(v - current) <= tolerance:
            count += 1
        else:
            fv = format_grdecl_value(current)
            tokens.append(f"{count}*{fv}" if count > 1 else fv)
            current = v
            count = 1

    fv = format_grdecl_value(current)
    tokens.append(f"{count}*{fv}" if count > 1 else fv)

    return tokens


def output_keyword_for_file(keyword: str) -> str:
    k = str(keyword).upper()

    replacements = {
        "PRESSURE_INIT": "PRESSURE",
        "PRESSURE_EOH": "PRESSURE",
        "SWAT_INIT": "SWAT",
        "SWAT_EOH": "SWAT",
        "SOIL_INIT": "SOIL",
        "SOIL_EOH": "SOIL",
        "SGAS_INIT": "SGAS",
        "SGAS_EOH": "SGAS",
        "PERM_X": "PERMX",
        "PERM_Y": "PERMY",
        "PERM_Z": "PERMZ",
    }

    return replacements.get(k, k)


def write_grdecl(path: Path, keyword: str, values: np.ndarray, values_per_line: int = 8) -> None:
    values = safe_float_array(values)
    out_keyword = output_keyword_for_file(keyword)
    tokens = compress_grdecl_values(values)

    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("-- Generated by 404 Reservoir Not Found extractor V4\n")
        f.write("-- Format      : ECLIPSE keywords (grid properties) (ASCII)\n")
        f.write("-- Note        : Values compressed using Eclipse N*VALUE syntax\n")
        f.write("-- Grid mask   : Petrel/INTERSECT GSG DEFINED_CELLS when available\n")
        f.write("\n")
        f.write("FILEUNIT\n")
        f.write("  FIELD /\n")
        f.write("\n")
        f.write(f"{out_keyword}\n")
        f.write(f"-- Output file name: {path.name}\n")

        for i in range(0, len(tokens), values_per_line):
            f.write("  " + " ".join(tokens[i:i + values_per_line]) + "\n")

        f.write("/\n")


def find_case_files(folder: Path) -> dict[str, list[Path]]:
    def rglob_many(patterns: list[str]) -> list[Path]:
        out = []
        for pat in patterns:
            out.extend(folder.rglob(pat))

        out = [
            p for p in out
            if "404_RNF_EXTRACTED_GRDECL" not in str(p)
            and p.is_file()
        ]

        return sorted(set(out))

    return {
        "gsg": rglob_many(["*.GSG", "*.gsg"]),
        "egrid": rglob_many(["*.EGRID", "*.GRID", "*.egrid", "*.grid"]),
        "init": rglob_many(["*.INIT", "*.init"]),
        "unrst": rglob_many(["*.UNRST", "*.unrst"]),
        "smspec": rglob_many(["*.SMSPEC", "*.smspec"]),
        "unsmry": rglob_many(["*.UNSMRY", "*.unsmry"]),
        "sln": rglob_many(["*.SLN*", "*.sln*"]),
        "text_input": rglob_many(["*.GRDECL", "*.grdecl", "*.INC", "*.inc", "*.IXF", "*.ixf", "*.DATA", "*.data", "*.AFI", "*.afi"]),
    }


def load_resdata():
    try:
        from resdata.resfile import ResdataFile
    except Exception as exc:
        raise RuntimeError("Could not import resdata. Install it with: pip install resdata") from exc

    return ResdataFile


def open_resfile(path: Path):
    ResdataFile = load_resdata()
    return ResdataFile(str(path))


def available_keywords(ecl_file: Any) -> list[str]:
    try:
        return sorted({norm_name(k) for k in list(ecl_file.keys())})
    except Exception:
        return []


def keyword_occurrences(ecl_file: Any, keyword: str) -> list[Any]:
    keyword = norm_name(keyword)

    try:
        obj = ecl_file[keyword]
        if isinstance(obj, (list, tuple)):
            return list(obj)
        try:
            return list(obj)
        except Exception:
            return [obj]
    except Exception:
        pass

    try:
        count = ecl_file.num_named_kw(keyword)
        out = []
        for i in range(count):
            out.append(ecl_file.iget_named_kw(keyword, i))
        return out
    except Exception:
        pass

    return []


def kw_to_numpy(kw: Any) -> np.ndarray:
    for method in ["numpy_copy", "numpyView", "numpy_view"]:
        if hasattr(kw, method):
            try:
                return safe_float_array(getattr(kw, method)())
            except Exception:
                pass

    try:
        return safe_float_array(list(kw))
    except Exception:
        return safe_float_array(kw)


def get_keyword_array(
    ecl_file: Any,
    possible_names: list[str],
    occurrence: str = "first",
) -> tuple[Optional[str], Optional[np.ndarray]]:
    for name in possible_names:
        key = norm_name(name)
        occ = keyword_occurrences(ecl_file, key)

        if not occ:
            continue

        kw = occ[-1] if occurrence == "last" else occ[0]
        return key, kw_to_numpy(kw)

    return None, None


def choose_init_file(files: dict[str, list[Path]], case: Optional[str]) -> Optional[Path]:
    init_files = files["init"]

    if not init_files:
        return None

    if case:
        for p in init_files:
            if p.stem.upper() == case.upper():
                return p

    # Prefer top-level INIT over nested if possible
    return sorted(init_files, key=lambda p: (len(p.parts), p.name))[0]


def choose_unrst_files(files: dict[str, list[Path]]) -> tuple[Optional[Path], Optional[Path]]:
    unrst = files["unrst"]

    if not unrst:
        return None, None

    unrst = sorted(unrst, key=lambda p: (len(p.parts), p.name))

    init_candidates = [p for p in unrst if "INIT" in p.name.upper()]
    eoh_candidates = [p for p in unrst if "EOH" in p.name.upper() or "END" in p.name.upper()]

    init_file = init_candidates[0] if init_candidates else unrst[0]
    eoh_file = eoh_candidates[-1] if eoh_candidates else unrst[-1]

    return init_file, eoh_file


def extract_actnum_from_resfile(path: Optional[Path]) -> Optional[np.ndarray]:
    if path is None:
        return None

    try:
        ecl = open_resfile(path)
    except Exception:
        return None

    for key in ["ACTNUM", "ACTIVE"]:
        source_kw, arr = get_keyword_array(ecl, [key], occurrence="first")
        if arr is not None and len(arr) > 0:
            return np.asarray(arr, dtype=float).reshape(-1)

    return None


def extract_actnum_from_available_files(
    init_file: Optional[Path],
    files: dict[str, list[Path]],
) -> tuple[Optional[np.ndarray], Optional[str]]:
    candidates = []

    if init_file is not None:
        candidates.append(init_file)

    candidates.extend(files.get("egrid", []))

    for p in candidates:
        actnum = extract_actnum_from_resfile(p)
        if actnum is not None:
            return actnum, str(p)

    return None, None


def parse_grdecl_values(path: Path) -> tuple[Optional[str], np.ndarray]:
    txt = path.read_text(encoding="utf-8", errors="ignore")

    txt = re.sub(r"--.*", "", txt)
    txt = re.sub(r"#.*", "", txt)
    txt = txt.replace("/", " ")

    tokens = txt.split()

    skip = {"FILEUNIT", "FIELD"}
    keyword = None
    start = 0

    for i, tok in enumerate(tokens):
        up = tok.upper()

        if up in skip:
            continue

        try:
            float(up)
            continue
        except Exception:
            pass

        if "*" in up:
            continue

        keyword = up
        start = i + 1
        break

    values = []

    for tok in tokens[start:]:
        t = tok.strip()

        if not t:
            continue

        if "*" in t:
            try:
                n_raw, v_raw = t.split("*", 1)
                n = int(n_raw)
                v = float(v_raw) if v_raw.strip() else 0.0
                values.extend([v] * n)
                continue
            except Exception:
                pass

        try:
            values.append(float(t))
        except Exception:
            pass

    return keyword, np.asarray(values, dtype=float)


def find_mask_grdecl(folder: Path, explicit: Optional[str]) -> Optional[Path]:
    if explicit:
        p = Path(explicit)
        if not p.is_absolute():
            p = folder / p
        return p if p.exists() else None

    preferred = [
        "FIPNUM.GRDECL",
        "PORO.GRDECL",
        "PERM_X.GRDECL",
        "SWAT_INIT.GRDECL",
    ]

    for name in preferred:
        p = folder / name
        if p.exists():
            return p

    candidates = []
    for pattern in ["*FIPNUM*.GRDECL", "*PORO*.GRDECL"]:
        candidates.extend(folder.glob(pattern))

    return sorted(candidates)[0] if candidates else None


def actnum_from_mask_grdecl(mask_path: Optional[Path]) -> tuple[Optional[np.ndarray], Optional[str], Optional[str]]:
    if mask_path is None:
        return None, None, None

    try:
        keyword, vals = parse_grdecl_values(mask_path)
    except Exception:
        return None, None, None

    if vals.size == 0:
        return None, None, None

    actnum = np.where(np.abs(vals) > 1e-14, 1.0, 0.0)

    return actnum, str(mask_path), keyword


def read_grid_dimensions_from_gsg(data: bytes) -> Optional[tuple[int, int, int]]:
    # COSTA case has NX/NY/NZ close to GRID header:
    # byte 162 = NX, 166 = NY, 170 = NZ.
    try:
        nx = struct.unpack("<i", data[162:166])[0]
        ny = struct.unpack("<i", data[166:170])[0]
        nz = struct.unpack("<i", data[170:174])[0]

        if 0 < nx < 10000 and 0 < ny < 10000 and 0 < nz < 10000:
            return nx, ny, nz
    except Exception:
        pass

    return None


def actnum_from_defined_cells_gsg(folder: Path) -> tuple[Optional[np.ndarray], Optional[str], Optional[dict[str, Any]]]:
    """
    Read Petrel/INTERSECT .GSG DEFINED_CELLS RLE mask.

    Pattern observed:
      DEFINED_CELLS
      global_count = NX * NY * NZ
      flag/version = 1
      RLE pairs: run_length, value

    Example pairs:
      159,0  9,1  169,0  14,1 ...
    """
    candidates = sorted([
        p for p in folder.rglob("*.GSG")
        if "404_RNF_EXTRACTED_GRDECL" not in str(p)
        and p.is_file()
        and p.name.upper() != "RESERVOIR.GSG"
    ], key=lambda p: p.stat().st_size)

    # Prefer top-level main case GSG; avoid property GSG first.
    candidates = sorted(
        candidates,
        key=lambda p: (
            any(x in p.name.upper() for x in ["POROSITY", "PERM", "REGION", "FLUID"]),
            len(p.parts),
            p.stat().st_size,
        )
    )

    for gsg_path in candidates:
        try:
            data = gsg_path.read_bytes()
        except Exception:
            continue

        name_pos = data.find(b"DEFINED_CELLS")
        if name_pos < 0:
            continue

        dims = read_grid_dimensions_from_gsg(data)
        possible_counts = []

        if dims is not None:
            nx, ny, nz = dims
            possible_counts.append(nx * ny * nz)
        else:
            nx = ny = nz = None

        # Fallback for COSTA if dimensions cannot be read.
        possible_counts.append(181 * 190 * 62)

        seen_counts = set()

        for global_count in possible_counts:
            if global_count in seen_counts:
                continue

            seen_counts.add(global_count)

            count_bytes = struct.pack("<i", int(global_count))
            count_pos = data.find(count_bytes, name_pos, name_pos + 2048)

            if count_pos < 0:
                continue

            # After global count there is one int flag/version.
            rle_start = count_pos + 8
            pos = rle_start
            mask_parts = []
            pairs_preview = []
            total = 0

            try:
                while total < global_count and pos + 8 <= len(data):
                    run_len = struct.unpack("<i", data[pos:pos + 4])[0]
                    value = struct.unpack("<i", data[pos + 4:pos + 8])[0]
                    pos += 8

                    if run_len < 0 or run_len > global_count:
                        raise ValueError(f"Invalid run length: {run_len}")

                    if value not in (0, 1):
                        raise ValueError(f"Invalid DEFINED_CELLS value: {value}")

                    if len(pairs_preview) < 20:
                        pairs_preview.append([int(run_len), int(value)])

                    mask_parts.append(np.full(run_len, value, dtype=np.uint8))
                    total += run_len

                if total == global_count:
                    mask = np.concatenate(mask_parts).astype(float)

                    meta = {
                        "source": str(gsg_path),
                        "defined_cells_position": int(name_pos),
                        "global_count_position": int(count_pos),
                        "global_count": int(global_count),
                        "nx": int(nx) if nx is not None else None,
                        "ny": int(ny) if ny is not None else None,
                        "nz": int(nz) if nz is not None else None,
                        "active_cells": int((mask > 0).sum()),
                        "inactive_cells": int((mask <= 0).sum()),
                        "first_rle_pairs": pairs_preview,
                    }

                    return mask, str(gsg_path), meta

            except Exception:
                continue

    return None, None, None


def expand_active_to_full_with_actnum(
    arr: np.ndarray,
    actnum: Optional[np.ndarray],
    fill_value: float = 0.0,
) -> tuple[np.ndarray, str]:
    arr = safe_float_array(arr)

    if actnum is None:
        return arr, "actnum_not_available"

    actnum = np.asarray(actnum).reshape(-1)
    active_mask = actnum > 0
    active_count = int(active_mask.sum())
    full_count = int(len(actnum))

    if len(arr) == full_count:
        return arr, "already_full_grid_actnum_length"

    if len(arr) == active_count:
        full = np.full(full_count, fill_value, dtype=float)
        full[active_mask] = arr
        return full, "expanded_active_to_full_using_actnum"

    return arr, f"actnum_length_mismatch_property={len(arr)} active={active_count} full={full_count}"


def extract_init_properties(
    out_dir: Path,
    init_file: Path,
    actnum: Optional[np.ndarray],
    report: dict[str, Any],
) -> None:
    ecl = open_resfile(init_file)
    kws = available_keywords(ecl)

    report["init_file"] = init_file.name
    report["init_path"] = str(init_file)
    report["init_available_keywords_sample"] = kws[:160]
    report["init_exports"] = {}

    for output_name, possible_names in INIT_EXPORTS.items():
        source_kw, arr = get_keyword_array(ecl, possible_names, occurrence="first")

        if arr is None:
            # Default multiplier fallback:
            # If MULTX/MULTY/MULTZ/PORO_MULT are not present in INIT,
            # generate neutral multipliers = 1 on active cells and 0 on inactive cells.
            if output_name in ["MULTX", "MULTY", "MULTZ", "PORO_MULT"] and actnum is not None:
                arr = np.where(np.asarray(actnum).reshape(-1) > 0, 1.0, 0.0)
                out_path = out_dir / f"{output_name}.GRDECL"
                write_grdecl(out_path, output_name, arr)

                report["init_exports"][output_name] = {
                    "status": "written_default",
                    "source_keyword": None,
                    "reason": "Property not found in INIT. Generated neutral multiplier = 1 on active cells and 0 on inactive cells using GSG DEFINED_CELLS mask.",
                    "file": out_path.name,
                    "raw_values": None,
                    "values": int(len(arr)),
                    "grid_mode": "default_from_actnum_mask",
                    "min": float(np.nanmin(arr)) if len(arr) else None,
                    "max": float(np.nanmax(arr)) if len(arr) else None,
                }
                continue

            report["init_exports"][output_name] = {
                "status": "missing",
                "searched_keywords": possible_names,
            }
            continue

        raw_values = int(len(arr))
        arr, mode = expand_active_to_full_with_actnum(arr, actnum)

        out_path = out_dir / f"{output_name}.GRDECL"
        write_grdecl(out_path, output_name, arr)

        report["init_exports"][output_name] = {
            "status": "written",
            "source_keyword": source_kw,
            "file": out_path.name,
            "raw_values": raw_values,
            "values": int(len(arr)),
            "grid_mode": mode,
            "min": float(np.nanmin(arr)) if len(arr) else None,
            "max": float(np.nanmax(arr)) if len(arr) else None,
        }


def extract_dynamic_properties(
    out_dir: Path,
    init_unrst_file: Optional[Path],
    eoh_unrst_file: Optional[Path],
    actnum: Optional[np.ndarray],
    report: dict[str, Any],
) -> None:
    report["dynamic_exports"] = {}
    report["dynamic_init_unrst_file"] = init_unrst_file.name if init_unrst_file else None
    report["dynamic_eoh_unrst_file"] = eoh_unrst_file.name if eoh_unrst_file else None

    if init_unrst_file is None or eoh_unrst_file is None:
        report["dynamic_status"] = "no_unrst_files_found"
        return

    init_ecl = open_resfile(init_unrst_file)
    eoh_ecl = open_resfile(eoh_unrst_file)

    report["dynamic_init_available_keywords_sample"] = available_keywords(init_ecl)[:160]
    report["dynamic_eoh_available_keywords_sample"] = available_keywords(eoh_ecl)[:160]

    for output_base, possible_names in DYNAMIC_EXPORTS.items():
        for label, ecl_file, occurrence, source_file in [
            ("INIT", init_ecl, "first", init_unrst_file),
            ("EOH", eoh_ecl, "last", eoh_unrst_file),
        ]:
            output_name = f"{output_base}_{label}"

            source_kw, arr = get_keyword_array(ecl_file, possible_names, occurrence=occurrence)

            if arr is None:
                report["dynamic_exports"][output_name] = {
                    "status": "missing",
                    "searched_keywords": possible_names,
                }
                continue

            raw_values = int(len(arr))
            arr, mode = expand_active_to_full_with_actnum(arr, actnum)

            out_path = out_dir / f"{output_name}.GRDECL"
            write_grdecl(out_path, output_name, arr)

            report["dynamic_exports"][output_name] = {
                "status": "written",
                "source_keyword": source_kw,
                "file": out_path.name,
                "raw_values": raw_values,
                "values": int(len(arr)),
                "grid_mode": mode,
                "time_label": label,
                "source_file": source_file.name,
                "source_path": str(source_file),
                "min": float(np.nanmin(arr)) if len(arr) else None,
                "max": float(np.nanmax(arr)) if len(arr) else None,
            }




def natural_sort_key(path: Path) -> list[Any]:
    parts = re.split(r"(\d+)", path.name.upper())
    out = []
    for p in parts:
        if p.isdigit():
            out.append(int(p))
        else:
            out.append(p)
    return out


def copy_standard_file(src: Optional[Path], dst: Path) -> Optional[dict[str, Any]]:
    if src is None or not src.exists():
        return None

    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)

    return {
        "source": str(src),
        "target": str(dst),
        "target_name": dst.name,
        "bytes": int(dst.stat().st_size),
    }


def write_grid_dimensions_json(out_dir: Path, folder: Path, report: dict[str, Any]) -> None:
    """
    Create grid_dimensions.json for the dashboard.

    Preferred source is the main .GSG containing DEFINED_CELLS / GRID dimensions.
    For the COSTA case, dimensions are stored at bytes 162/166/170:
      NX=181, NY=190, NZ=62
    """
    dims = None
    source = None

    candidates = sorted([
        p for p in folder.rglob("*.GSG")
        if "404_RNF_EXTRACTED_GRDECL" not in str(p)
        and p.is_file()
        and p.name.upper() != "RESERVOIR.GSG"
    ], key=lambda p: (
        any(x in p.name.upper() for x in ["POROSITY", "PERM", "REGION", "FLUID"]),
        len(p.parts),
        p.stat().st_size,
    ))

    for p in candidates:
        try:
            data = p.read_bytes()
            d = read_grid_dimensions_from_gsg(data)
            if d is not None:
                dims = d
                source = p
                break
        except Exception:
            continue

    if dims is None:
        report.setdefault("warnings", []).append(
            "Could not infer grid dimensions from GSG. grid_dimensions.json was not created."
        )
        return

    nx, ny, nz = dims
    payload = {
        "nx": int(nx),
        "ny": int(ny),
        "nz": int(nz),
    }

    out_path = out_dir / "grid_dimensions.json"
    out_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    report["grid_dimensions_json"] = {
        "file": out_path.name,
        "source": str(source),
        "nx": int(nx),
        "ny": int(ny),
        "nz": int(nz),
        "cells": int(nx * ny * nz),
    }


def find_well_connections_file(folder: Path) -> Optional[Path]:
    candidates = [
        p for p in folder.rglob("*.ixf")
        if "404_RNF_EXTRACTED_GRDECL" not in str(p)
        and "WELL_CONNECTION" in p.name.upper()
    ]
    return sorted(candidates, key=lambda p: (-p.stat().st_size, str(p)))[0] if candidates else None


def find_relperm_file(folder: Path) -> Optional[Path]:
    """
    For Petrel/INTERSECT exports, relperm curves are commonly in ROCKS.ixf.
    Prefer explicit RELPERM names, then ROCKS.
    """
    all_ixf = [
        p for p in folder.rglob("*.ixf")
        if "404_RNF_EXTRACTED_GRDECL" not in str(p)
    ]

    priority = []

    for p in all_ixf:
        n = p.name.upper()
        score = 0

        if "RELPERM" in n or "REL_PERM" in n or "RELATIVE" in n:
            score += 100
        if "ROCK" in n:
            score += 80
        if "FLUID" in n:
            score += 20

        if score > 0:
            priority.append((score, p.stat().st_size, p))

    if priority:
        priority.sort(reverse=True, key=lambda x: (x[0], x[1]))
        return priority[0][2]

    # Content fallback: search small IXF files for relperm keywords.
    for p in sorted(all_ixf, key=lambda x: x.stat().st_size):
        try:
            if p.stat().st_size > 20_000_000:
                continue
            txt = p.read_text(encoding="utf-8", errors="ignore").upper()
            if any(k in txt for k in ["RELATIVE_PERMEABILITY", "KRW", "KRO", "KRG", "SATURATION_FUNCTION"]):
                return p
        except Exception:
            continue

    return None




def _extract_braced_blocks(txt: str, block_regex: str) -> list[tuple[str, str]]:
    """
    Return [(model_name, full_block_text)] for top-level braced blocks.
    """
    blocks = []
    pattern = re.compile(block_regex, re.I | re.M)

    pos = 0
    while True:
        m = pattern.search(txt, pos)
        if not m:
            break

        model = m.group(1)
        brace_start = txt.find("{", m.start())
        if brace_start < 0:
            break

        depth = 0
        end = None

        for i in range(brace_start, len(txt)):
            ch = txt[i]
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    end = i + 1
                    break

        if end is None:
            break

        blocks.append((model, txt[m.start():end].strip()))
        pos = end

    return blocks


def _parse_table_from_block(block: str, table_name: str) -> list[list[float]]:
    """
    Parse a bracket table like:

      GasOilFunction [
          GasSaturation GasRelPerm OilRelPerm CapPressure
          0 0 1 0
      ]

    Returns numeric rows only.
    """
    pat = re.compile(r'\b' + re.escape(table_name) + r'\s*\[(.*?)\]', re.I | re.S)
    m = pat.search(block)
    if not m:
        return []

    body = m.group(1)
    rows = []

    for line in body.splitlines():
        clean = re.sub(r"--.*", "", line).strip()
        if not clean:
            continue

        vals = []
        ok = True

        for tok in clean.split():
            try:
                vals.append(float(tok))
            except Exception:
                ok = False
                break

        if ok and vals:
            rows.append(vals)

    return rows


def _fmt_num(x: float) -> str:
    x = float(x)
    if abs(x) < 1e-14:
        return "0"
    if abs(x - round(x)) < 1e-12:
        return str(int(round(x)))
    return f"{x:.12g}"


def _write_two_col_table(title: str, col1: str, col2: str, rows: list[tuple[float, float]]) -> str:
    out = []
    out.append(f'    {title} [')
    out.append(f'        {col1:>16}    {col2:>16}')
    for a, b in rows:
        out.append(f'        {_fmt_num(a):>16}    {_fmt_num(b):>16}')
    out.append('    ]')
    return "\n".join(out)


def _convert_twophase_block_to_petrel_saturation_function(model: str, block: str) -> Optional[str]:
    gas_rows = _parse_table_from_block(block, "GasOilFunction")
    ow_rows = _parse_table_from_block(block, "OilWaterFunction")

    if not gas_rows and not ow_rows:
        return None

    parts = []
    parts.append(f'SaturationFunction "{model}" {{')

    if ow_rows:
        # Columns: WaterSaturation, WaterRelPerm, OilRelPerm, CapPressure
        pcow = [(r[0], r[3]) for r in ow_rows if len(r) >= 4]
        krw = [(r[0], r[1]) for r in ow_rows if len(r) >= 2]
        krow = [(1.0 - r[0], r[2]) for r in ow_rows if len(r) >= 3]
        krow = sorted(krow, key=lambda x: x[0])

        parts.append(_write_two_col_table('CapPressure "Pcow_v_Sw"', "Saturation", "CapPressure", pcow))
        parts.append("")
    else:
        pcow = []

    if gas_rows:
        # Columns: GasSaturation, GasRelPerm, OilRelPerm, CapPressure
        pcgo = [(r[0], r[3]) for r in gas_rows if len(r) >= 4]
        krg = [(r[0], r[1]) for r in gas_rows if len(r) >= 2]

        sg_max = max((r[0] for r in gas_rows if len(r) >= 1), default=1.0)
        krog = [(sg_max - r[0], r[2]) for r in gas_rows if len(r) >= 3]
        krog = sorted(krog, key=lambda x: x[0])

        parts.append(_write_two_col_table('CapPressure "Pcgo_v_Sg"', "Saturation", "CapPressure", pcgo))
        parts.append("")
        parts.append(_write_two_col_table('RelPerm "Krg_v_Sg"', "Saturation", "RelPerm", krg))
        parts.append("")
        parts.append(_write_two_col_table('RelPerm "Krog_v_So"', "Saturation", "RelPerm", krog))
        parts.append("")

    if ow_rows:
        parts.append(_write_two_col_table('RelPerm "Krw_v_Sw"', "Saturation", "RelPerm", krw))
        parts.append("")
        parts.append(_write_two_col_table('RelPerm "Krow_v_So"', "Saturation", "RelPerm", krow))
        parts.append("")

    parts.append("}")

    return "\n".join(parts)


def extract_petrel_saturation_functions_ixf(src: Path, dst: Path) -> Optional[dict[str, Any]]:
    """
    Build RELPERM.ixf in the old dashboard-compatible format.

    Priority:
    1. If standalone Petrel-style SaturationFunction blocks exist, copy only those.
    2. Otherwise convert TwoPhaseSaturationFunction blocks into old-style:
       CapPressure + RelPerm tables.
    """
    if src is None or not src.exists():
        return None

    txt = src.read_text(encoding="utf-8", errors="ignore")

    # Important: anchored pattern. This does NOT match TwoPhaseSaturationFunction.
    standalone = _extract_braced_blocks(
        txt,
        r'^\s*SaturationFunction\s+"([^"]+)"\s*\{'
    )

    blocks = []
    mode = None

    if standalone:
        blocks = [b for _, b in standalone]
        mode = "extracted_original_petrel_saturationfunction_blocks"
    else:
        twophase = _extract_braced_blocks(
            txt,
            r'^\s*TwoPhaseSaturationFunction\s+"([^"]+)"\s*\{'
        )

        for model, block in twophase:
            converted = _convert_twophase_block_to_petrel_saturation_function(model, block)
            if converted:
                blocks.append(converted)

        if blocks:
            mode = "converted_twophase_to_petrel_saturationfunction_blocks"

    if not blocks:
        return None

    dst.parent.mkdir(parents=True, exist_ok=True)

    header = """######################################
# IXFVERSION: 2023.4 Petrel
# Generated by 404 Reservoir Not Found extractor V4
# RELPERM format: dashboard-compatible SaturationFunction blocks
######################################

MODEL_DEFINITION

Units {
    UnitSystem=ECLIPSE_FIELD
}

"""

    dst.write_text(header + "\n\n".join(blocks) + "\n", encoding="utf-8", newline="\n")

    return {
        "source": str(src),
        "target": str(dst),
        "target_name": dst.name,
        "bytes": int(dst.stat().st_size),
        "mode": mode,
        "saturation_function_blocks": int(len(blocks)),
    }

def find_prt_file(folder: Path) -> Optional[Path]:
    candidates = []

    for pat in ["*.PRT", "*.prt", "*.OUT", "*.out", "*.LOG", "*.log"]:
        candidates.extend(folder.rglob(pat))

    candidates = [
        p for p in candidates
        if "404_RNF_EXTRACTED_GRDECL" not in str(p)
        and p.is_file()
    ]

    if not candidates:
        return None

    # Prefer explicit PRT, then largest report-like file.
    candidates.sort(key=lambda p: (
        0 if p.suffix.upper() == ".PRT" else 1,
        -p.stat().st_size,
        str(p)
    ))

    return candidates[0]


def extract_sln_number(path: Path) -> Optional[int]:
    """
    Extract the numeric suffix from streamline files.

    Supported examples:
      CASE.SLN001
      CASE.SLN0001
      CASE.SLN359
      CASE.sln0359
    """
    m = re.search(r"\.SLN(\d+)$", path.name, flags=re.I)
    if not m:
        return None
    return int(m.group(1))


def find_streamline_files(folder: Path) -> tuple[Optional[Path], Optional[Path]]:
    """
    Pick initial and end-of-history streamline files by numeric SLN suffix.

    Initial = lowest SLN number.
    EOH     = highest SLN number.

    This avoids lexicographic mistakes and avoids choosing unrelated files.
    """
    candidates = []

    for p in folder.rglob("*"):
        if not p.is_file():
            continue

        if "404_RNF_EXTRACTED_GRDECL" in str(p):
            continue

        sln_number = extract_sln_number(p)
        if sln_number is None:
            continue

        candidates.append((sln_number, p))

    if not candidates:
        return None, None

    candidates.sort(key=lambda x: (x[0], x[1].name.upper()))

    init_file = candidates[0][1]
    eoh_file = candidates[-1][1]

    return init_file, eoh_file

def collect_support_files(folder: Path, out_dir: Path, report: dict[str, Any]) -> None:
    """
    Copy/canonicalize non-GRDECL support files needed by dashboard workflows:
      - grid_dimensions.json
      - WELL_CONNECTIONS.ixf
      - RELPERM.ixf
      - SIMULATION.PRT
      - STREAMLINES_INIT.SLNxxxx
      - STREAMLINES_EOH.SLNxxxx
    """
    support = {}

    write_grid_dimensions_json(out_dir, folder, report)

    well_conn = find_well_connections_file(folder)
    copied = copy_standard_file(well_conn, out_dir / "WELL_CONNECTIONS.ixf")
    if copied:
        support["well_connections"] = copied
    else:
        report.setdefault("warnings", []).append("WELL_CONNECTIONS.ixf not found.")

    relperm = find_relperm_file(folder)

    # Build a clean RELPERM.ixf with only original Petrel SaturationFunction blocks.
    copied = extract_petrel_saturation_functions_ixf(relperm, out_dir / "RELPERM.ixf") if relperm else None

    # Fallback: copy the source as-is only if clean extraction failed.
    if copied is None:
        copied = copy_standard_file(relperm, out_dir / "RELPERM.ixf")

    if copied:
        support["relperm"] = copied
    else:
        report.setdefault("warnings", []).append("RELPERM/ROCKS IXF file not found or no SaturationFunction blocks detected.")

    prt = find_prt_file(folder)
    copied = copy_standard_file(prt, out_dir / "SIMULATION.PRT")
    if copied:
        support["prt"] = copied
    else:
        report.setdefault("warnings", []).append("PRT/OUT/LOG simulator report not found.")

    sln_init, sln_eoh = find_streamline_files(folder)

    if sln_init is not None:
        init_suffix = sln_init.suffix if sln_init.suffix else ".SLN0001"
        copied = copy_standard_file(sln_init, out_dir / f"STREAMLINES_INIT{init_suffix}")
        if copied:
            support["streamlines_init"] = copied
    else:
        report.setdefault("warnings", []).append("Initial streamline file not found.")

    if sln_eoh is not None:
        eoh_suffix = sln_eoh.suffix if sln_eoh.suffix else ".SLN_EOH"
        copied = copy_standard_file(sln_eoh, out_dir / f"STREAMLINES_EOH{eoh_suffix}")
        if copied:
            support["streamlines_eoh"] = copied
    else:
        report.setdefault("warnings", []).append("End-of-history streamline file not found.")

    report["support_files"] = support


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract 404 RNF dashboard GRDECL properties from a completed INTERSECT/Petrel run folder."
    )
    parser.add_argument("--folder", default=".", help="Completed run folder. Default: current folder.")
    parser.add_argument("--case", default=None, help="Optional case basename, e.g. MYCASE for MYCASE.INIT.")
    parser.add_argument("--out", default="404_RNF_EXTRACTED_GRDECL", help="Output folder for generated GRDECL files.")
    parser.add_argument(
        "--mask-grdecl",
        default=None,
        help="Optional full-grid Petrel GRDECL used as fallback active-cell mask, preferably FIPNUM.GRDECL or PORO.GRDECL.",
    )

    args = parser.parse_args()

    folder = Path(args.folder).resolve()
    out_dir = (folder / args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    files = find_case_files(folder)

    report: dict[str, Any] = {
        "script": "extract_404_rnf_grdecl_from_run_v4.py",
        "version": "V4_GSG_DEFINED_CELLS_MASK",
        "folder": str(folder),
        "output_folder": str(out_dir),
        "files_found": {k: [str(p.relative_to(folder)) if p.is_relative_to(folder) else str(p) for p in v] for k, v in files.items()},
        "warnings": [],
    }

    init_file = choose_init_file(files, args.case)

    # 1. Try binary ACTNUM.
    actnum, actnum_source = extract_actnum_from_available_files(init_file, files)
    actnum_method = "binary_ACTNUM"

    # 2. Try GSG DEFINED_CELLS mask.
    if actnum is None:
        actnum, actnum_source, gsg_meta = actnum_from_defined_cells_gsg(folder)
        if actnum is not None:
            actnum_method = "GSG_DEFINED_CELLS"
            report["actnum_mask_gsg_defined_cells"] = gsg_meta

    # 3. Fallback to GRDECL mask.
    if actnum is None:
        mask_path = find_mask_grdecl(folder, args.mask_grdecl)
        actnum, actnum_source, mask_keyword = actnum_from_mask_grdecl(mask_path)
        if actnum is not None:
            actnum_method = "GRDECL_MASK"
            report["actnum_mask_grdecl"] = {
                "source": actnum_source,
                "keyword": mask_keyword,
                "method": "active where mask value is non-zero",
            }

    if actnum is not None:
        report["actnum"] = {
            "source": actnum_source,
            "method": actnum_method,
            "cells": int(len(actnum)),
            "active_cells": int((actnum > 0).sum()),
            "inactive_cells": int((actnum <= 0).sum()),
        }
    else:
        report["actnum"] = {
            "source": None,
            "status": "not_available",
        }

    if init_file is None:
        report["warnings"].append("No .INIT file found. Static INIT properties were not extracted.")
    else:
        try:
            extract_init_properties(out_dir, init_file, actnum, report)
        except Exception as exc:
            report["warnings"].append(f"INIT extraction failed for {init_file.name}: {exc}")

    init_unrst, eoh_unrst = choose_unrst_files(files)

    try:
        extract_dynamic_properties(out_dir, init_unrst, eoh_unrst, actnum, report)
    except Exception as exc:
        report["warnings"].append(f"Dynamic UNRST extraction failed: {exc}")

    collect_support_files(folder, out_dir, report)

    report_path = out_dir / "404_RNF_EXTRACTION_REPORT.json"
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")

    print("")
    print("404 RNF GRDECL extraction V4 completed.")
    print(f"Run folder:        {folder}")
    print(f"Output folder:     {out_dir}")
    print(f"Extraction report: {report_path}")
    print("")

    if actnum is not None:
        print("Grid mask:")
        print(f"  method:         {actnum_method}")
        print(f"  source:         {actnum_source}")
        print(f"  cells:          {len(actnum):,}")
        print(f"  active cells:   {int((actnum > 0).sum()):,}")
        print(f"  inactive cells: {int((actnum <= 0).sum()):,}")
    else:
        print("Grid mask: NOT AVAILABLE")
        print("Properties will remain active-cell arrays and may not plot correctly as full-grid maps.")

    print("")

    written = []
    for section in ["init_exports", "dynamic_exports"]:
        for name, info in report.get(section, {}).items():
            if info.get("status") == "written":
                written.append(info.get("file"))

    if written:
        print("Generated GRDECL files:")
        for f in sorted(set(written)):
            print(f"  - {f}")
    else:
        print("No GRDECL files were generated. Check 404_RNF_EXTRACTION_REPORT.json.")

    if report.get("warnings"):
        print("")
        print("Warnings:")
        for w in report["warnings"]:
            print(f"  - {w}")


if __name__ == "__main__":
    main()
