from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List


ROOT = Path(__file__).resolve().parents[1]
DIAG_DIR = ROOT / "artifacts" / "diagnosis"

MODULES = [
    "app.driver_diagnosis",
    "app.export_oil_profile_diagnostics",
    "app.export_gas_profile_diagnostics",
    "app.export_bhp_profile_diagnostics",
    "app.bhp_observed_filter",
    "app.well_activity_classifier",
    "app.smart_well_recommendation_agent",
]

REQUIRED_OUTPUTS = [
    "well_property_driver_context.csv",
    "water_driver_diagnosis.json",
    "driver_diagnosis_summary.json",
    "oil_profile_diagnostics.json",
    "gas_profile_diagnostics.json",
    "bhp_profile_diagnostics.json",
    "bhp_observed_filter_report.json",
    "well_activity_classification.json",
    "well_activity_classification.csv",
    "smart_well_recommendations.json",
    "smart_well_recommendations.csv",
]


def run_diagnostics_pipeline(reason: str = "manual", strict: bool = False) -> Dict[str, Any]:
    """
    Run existing deterministic post-processing scripts after a case is imported
    or activated. These scripts read data/sample_model and write artifacts/diagnosis.
    No LLM-generated KPI is created here.
    """
    DIAG_DIR.mkdir(parents=True, exist_ok=True)

    results: List[Dict[str, Any]] = []

    for module in MODULES:
        started_at = datetime.utcnow().isoformat() + "Z"

        try:
            proc = subprocess.run(
                [sys.executable, "-m", module],
                cwd=str(ROOT),
                capture_output=True,
                text=True,
                timeout=300,
            )

            results.append({
                "module": module,
                "started_at": started_at,
                "returncode": proc.returncode,
                "ok": proc.returncode == 0,
                "stdout_tail": (proc.stdout or "")[-5000:],
                "stderr_tail": (proc.stderr or "")[-5000:],
            })

        except Exception as exc:
            results.append({
                "module": module,
                "started_at": started_at,
                "returncode": None,
                "ok": False,
                "error": f"{type(exc).__name__}: {exc}",
            })

    missing = [name for name in REQUIRED_OUTPUTS if not (DIAG_DIR / name).exists()]
    failed = [r for r in results if not r.get("ok")]

    payload: Dict[str, Any] = {
        "reason": reason,
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "root": str(ROOT),
        "diagnosis_dir": str(DIAG_DIR),
        "modules": results,
        "required_outputs": REQUIRED_OUTPUTS,
        "missing_outputs": missing,
        "failed_modules": [r.get("module") for r in failed],
        "ok": not missing and not failed,
        "note": (
            "Diagnostics generated by existing deterministic reservoir scripts. "
            "No diagnosis artifact is generated by the LLM."
        ),
    }

    report_path = DIAG_DIR / "diagnostics_pipeline_report.json"
    report_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    if strict and not payload["ok"]:
        raise RuntimeError(
            "Diagnostics pipeline failed. "
            f"Missing outputs: {missing}; failed modules: {[r.get('module') for r in failed]}"
        )

    return payload


if __name__ == "__main__":
    result = run_diagnostics_pipeline(reason="cli", strict=False)
    print(json.dumps(
        {
            "ok": result["ok"],
            "missing": result["missing_outputs"],
            "failed": result["failed_modules"],
            "report": str(DIAG_DIR / "diagnostics_pipeline_report.json"),
        },
        indent=2,
    ))
    raise SystemExit(0 if result["ok"] else 1)
